[build]
backend = "python"
params = { "railwaypythonxref" = "3.11" }

[deploy]
build = "cd frontend && npm install && npm run build && ls -la ../backend/static && cp -r dist ../backend/static"

[postBuildCommand]
command = "ls -la backend/static"